// Package trace defines types for recording real execution traces of database
// operations. Traces are generated by actual execution paths, not fabricated
// display text. This package defines the types only; wiring into engine
// components is deferred to Phase 15.
package trace

import (
	"encoding/json"
	"fmt"
	"time"
)

// OperationType identifies the high-level database operation being traced.
type OperationType string

const (
	OpGet          OperationType = "GET"
	OpPut          OperationType = "PUT"
	OpDelete       OperationType = "DELETE"
	OpScan         OperationType = "SCAN"
	OpVectorSearch OperationType = "VECTOR_SEARCH"
	OpVectorInsert OperationType = "VECTOR_INSERT"
	OpRoute        OperationType = "ROUTE"
	OpReplicate    OperationType = "REPLICATE"
	OpFlush        OperationType = "FLUSH"
	OpCompact      OperationType = "COMPACT"
)

// Component identifies which layer of the engine produced a trace step.
type Component string

const (
	ComponentCLI      Component = "CLI"
	ComponentRouter   Component = "ROUTER"
	ComponentNode     Component = "NODE"
	ComponentEngine   Component = "ENGINE"
	ComponentWAL      Component = "WAL"
	ComponentMemTable Component = "MEMTABLE"
	ComponentSSTable  Component = "SSTABLE"
	ComponentBloom    Component = "BLOOM"
	ComponentVector   Component = "VECTOR"
	ComponentShard    Component = "SHARD"
	ComponentReplica  Component = "REPLICA"
	ComponentNetwork  Component = "NETWORK"
)

// StepType describes what happened at a particular step in the execution path.
type StepType string

const (
	// Read path steps
	StepTypeMemTableHit  StepType = "MEMTABLE_HIT"
	StepTypeMemTableMiss StepType = "MEMTABLE_MISS"
	StepTypeBloomSkip    StepType = "BLOOM_SKIP"  // Bloom filter excluded this SSTable
	StepTypeBloomCheck   StepType = "BLOOM_CHECK" // Bloom filter said "maybe present"
	StepTypeSSTableHit   StepType = "SSTABLE_HIT"
	StepTypeSSTableMiss  StepType = "SSTABLE_MISS"
	StepTypeNotFound     StepType = "NOT_FOUND"

	// Write path steps
	StepTypeWALAppend      StepType = "WAL_APPEND"
	StepTypeMemTablePut    StepType = "MEMTABLE_PUT"
	StepTypeMemTableDelete StepType = "MEMTABLE_DELETE"

	// Flush / compact steps
	StepTypeFlushStart      StepType = "FLUSH_START"
	StepTypeFlushComplete   StepType = "FLUSH_COMPLETE"
	StepTypeCompactStart    StepType = "COMPACT_START"
	StepTypeCompactComplete StepType = "COMPACT_COMPLETE"

	// Vector steps
	StepTypeVectorLoad    StepType = "VECTOR_LOAD"
	StepTypeVectorCompute StepType = "VECTOR_COMPUTE"
	StepTypeVectorTopK    StepType = "VECTOR_TOPK"

	// Vector write steps (Phase 22)
	StepTypeVectorValidate    StepType = "VECTOR_VALIDATE"
	StepTypeVectorEncode      StepType = "VECTOR_ENCODE"
	StepTypeVectorEngineWrite StepType = "VECTOR_ENGINE_WRITE"
	StepTypeVectorIndexUpdate StepType = "VECTOR_INDEX_UPDATE"
	StepTypeVectorIndexDelete StepType = "VECTOR_INDEX_DELETE"

	// Key validation step (Phase 22)
	StepTypeKeyValidated StepType = "KEY_VALIDATED"

	// SSTable bounds skip (Phase 22)
	StepTypeBoundsSkip StepType = "BOUNDS_SKIP"

	// Scan steps (Phase 22)
	StepTypeScanSource StepType = "SCAN_SOURCE"
	StepTypeScanMerge  StepType = "SCAN_MERGE"

	// Routing steps
	StepTypeRingLookup StepType = "RING_LOOKUP"
	StepTypeNodeCall   StepType = "NODE_CALL"

	// Replication steps
	StepTypeReplicateAppend StepType = "REPLICATE_APPEND"
	StepTypeReplicatePull   StepType = "REPLICATE_PULL"
	StepTypeReplicateApply  StepType = "REPLICATE_APPLY"
)

// Status indicates whether a step succeeded, was skipped, or failed.
type Status string

const (
	StatusOK      Status = "OK"
	StatusSkipped Status = "SKIPPED"
	StatusError   Status = "ERROR"
)

// TraceStep records one execution step within an operation.
type TraceStep struct {
	// Component is the engine layer that produced this step.
	Component Component `json:"component"`

	// StepType describes what happened.
	StepType StepType `json:"step_type"`

	// Status is the outcome of this step.
	Status Status `json:"status"`

	// Duration is the wall-clock time spent in this step.
	// Zero means the step was instantaneous or not measured.
	Duration time.Duration `json:"duration_ns"`

	// Detail is a human-readable description of this step.
	// Examples: "key=user:1", "sstable=000003.sst", "bloom_fp_rate=0.01"
	Detail string `json:"detail,omitempty"`

	// Metadata holds structured key-value pairs for this step.
	// Keys and values must be safe to expose (no passwords, no raw values).
	Metadata map[string]string `json:"metadata,omitempty"`
}

// Trace records the full execution trace of a single database operation.
// All steps are in execution order. Durations are real measurements.
type Trace struct {
	// ID is a unique identifier for this trace (set by the caller).
	ID string `json:"id,omitempty"`

	// Operation is the type of database operation being traced.
	Operation OperationType `json:"operation"`

	// Key is the key involved in the operation (may be empty for scans).
	Key string `json:"key,omitempty"`

	// StartedAt is when the operation began.
	StartedAt time.Time `json:"started_at"`

	// FinishedAt is when the operation completed. Zero if not yet finished.
	FinishedAt time.Time `json:"finished_at,omitempty"`

	// Steps are the execution steps in order.
	Steps []TraceStep `json:"steps"`

	// Err is set if the operation returned an error.
	Err string `json:"error,omitempty"`
}

// New creates a new Trace for the given operation and key.
func New(op OperationType, key string) *Trace {
	return &Trace{
		Operation: op,
		Key:       key,
		StartedAt: time.Now(),
		Steps:     make([]TraceStep, 0, 8),
	}
}

// NewWithID creates a new Trace with an explicit ID.
func NewWithID(id string, op OperationType, key string) *Trace {
	t := New(op, key)
	t.ID = id
	return t
}

// AddStep appends a step to the trace.
func (t *Trace) AddStep(step TraceStep) {
	t.Steps = append(t.Steps, step)
}

// Step is a convenience builder that appends a step and returns the trace
// for chaining.
func (t *Trace) Step(component Component, stepType StepType, status Status, duration time.Duration, detail string) *Trace {
	t.Steps = append(t.Steps, TraceStep{
		Component: component,
		StepType:  stepType,
		Status:    status,
		Duration:  duration,
		Detail:    detail,
	})
	return t
}

// Finish marks the trace as complete. If err is non-nil, it is recorded.
func (t *Trace) Finish(err error) {
	t.FinishedAt = time.Now()
	if err != nil {
		t.Err = err.Error()
	}
}

// TotalDuration returns the wall-clock duration of the entire operation.
// Returns zero if FinishedAt is not set.
func (t *Trace) TotalDuration() time.Duration {
	if t.FinishedAt.IsZero() {
		return 0
	}
	return t.FinishedAt.Sub(t.StartedAt)
}

// StepDurationSum returns the sum of all individual step durations.
func (t *Trace) StepDurationSum() time.Duration {
	var total time.Duration
	for _, s := range t.Steps {
		total += s.Duration
	}
	return total
}

// StepsWithStatus returns all steps matching the given status.
func (t *Trace) StepsWithStatus(s Status) []TraceStep {
	var out []TraceStep
	for _, step := range t.Steps {
		if step.Status == s {
			out = append(out, step)
		}
	}
	return out
}

// StepsForComponent returns all steps produced by the given component.
func (t *Trace) StepsForComponent(c Component) []TraceStep {
	var out []TraceStep
	for _, step := range t.Steps {
		if step.Component == c {
			out = append(out, step)
		}
	}
	return out
}

// MarshalJSON implements json.Marshaler. Duration is serialized as nanoseconds.
func (t *Trace) MarshalJSON() ([]byte, error) {
	type Alias struct {
		ID         string        `json:"id,omitempty"`
		Operation  OperationType `json:"operation"`
		Key        string        `json:"key,omitempty"`
		StartedAt  time.Time     `json:"started_at"`
		FinishedAt *time.Time    `json:"finished_at,omitempty"`
		TotalNs    int64         `json:"total_duration_ns"`
		StepSumNs  int64         `json:"step_sum_ns"`
		Steps      []TraceStep   `json:"steps"`
		Err        string        `json:"error,omitempty"`
	}
	a := Alias{
		ID:        t.ID,
		Operation: t.Operation,
		Key:       t.Key,
		StartedAt: t.StartedAt,
		Steps:     t.Steps,
		Err:       t.Err,
		TotalNs:   int64(t.TotalDuration()),
		StepSumNs: int64(t.StepDurationSum()),
	}
	if !t.FinishedAt.IsZero() {
		ft := t.FinishedAt
		a.FinishedAt = &ft
	}
	return json.Marshal(a)
}

// String returns a human-readable summary of the trace.
func (t *Trace) String() string {
	status := "OK"
	if t.Err != "" {
		status = "ERROR: " + t.Err
	}
	return fmt.Sprintf("Trace[%s key=%q steps=%d total=%v status=%s]",
		t.Operation, t.Key, len(t.Steps), t.TotalDuration(), status)
}
